#!/bin/bash
#   WAN/external = ens192  (10.240.101.85)
#   LAN/internal = ens224  (192.168.10.1)
iptables -F
iptables -t nat -F
iptables -X

echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
iptables -A INPUT  -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A INPUT   -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT  -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

# PART 1 RULES
iptables -A INPUT  -i ens224 -s 192.168.10.0/24 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -o ens224 -d 192.168.10.0/24 -p tcp --sport 22 -j ACCEPT
iptables -A INPUT  -i ens192 -p tcp --dport 21 -j ACCEPT
iptables -A INPUT  -i ens192 -p tcp --dport 20 -j ACCEPT
iptables -A OUTPUT -o ens192 -p tcp --sport 21 -j ACCEPT
iptables -A OUTPUT -o ens192 -p tcp --sport 20 -j ACCEPT


# PART 2 WEB to FILESERVER1
iptables -t nat -A PREROUTING -i ens192 -p tcp --dport 80 \
  -j DNAT --to-destination 192.168.10.2:80

# Forwarded traffic to reach FS1 and replies back
iptables -A FORWARD -i ens192 -o ens224 -p tcp -d 192.168.10.2 --dport 80 -j ACCEPT
iptables -A FORWARD -i ens224 -o ens192 -p tcp -s 192.168.10.2 --sport 80 -j ACCEPT

#
iptables -A FORWARD -i ens224 -o ens192 -p udp --dport 53 -j ACCEPT
iptables -A FORWARD -i ens192 -o ens224 -p udp --sport 53 -j ACCEPT

iptables -A FORWARD -i ens224 -o ens192 -p tcp --dport 53 -j ACCEPT
iptables -A FORWARD -i ens192 -o ens224 -p tcp --sport 53 -j ACCEPT

iptables -A FORWARD -i ens224 -o ens192 -p icmp --icmp-type echo-request -j ACCEPT
iptables -A FORWARD -i ens192 -o ens224 -p icmp --icmp-type echo-reply   -j ACCEPT

iptables -A FORWARD -i ens224 -o ens192 -p tcp --dport 80  -j ACCEPT
iptables -A FORWARD -i ens224 -o ens192 -p tcp --dport 443 -j ACCEPT

iptables -t nat -A POSTROUTING -o ens192 -j MASQUERADE

